/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BondManagerContract } from "./BondManager";
import { CanonicalTransactionChainContract } from "./CanonicalTransactionChain";
import { FraudVerifierContract } from "./FraudVerifier";
import { OwnableContract } from "./Ownable";
import { StateCommitmentChainContract } from "./StateCommitmentChain";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BondManager"): BondManagerContract;
      require(
        name: "CanonicalTransactionChain"
      ): CanonicalTransactionChainContract;
      require(name: "FraudVerifier"): FraudVerifierContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "StateCommitmentChain"): StateCommitmentChainContract;
    }
  }
}

export { BondManagerContract, BondManagerInstance } from "./BondManager";
export {
  CanonicalTransactionChainContract,
  CanonicalTransactionChainInstance,
} from "./CanonicalTransactionChain";
export { FraudVerifierContract, FraudVerifierInstance } from "./FraudVerifier";
export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  StateCommitmentChainContract,
  StateCommitmentChainInstance,
} from "./StateCommitmentChain";
